/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.vmsc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.vmsc.parser.antlr.internal.InternalVmscParser;
import org.xtext.example.vmsc.services.VmscGrammarAccess;

public class VmscParser extends AbstractAntlrParser {

	@Inject
	private VmscGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVmscParser createParser(XtextTokenStream stream) {
		return new InternalVmscParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "VPackage";
	}

	public VmscGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VmscGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
