/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.vmsc.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.vmsc.ui.internal.VmscActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VmscExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VmscActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VmscActivator activator = VmscActivator.getInstance();
		return activator != null ? activator.getInjector(VmscActivator.ORG_XTEXT_EXAMPLE_VMSC_VMSC) : null;
	}

}
