import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { VmscGeneratedModule, VmscGeneratedSharedModule } from './generated/module';
import { VmscValidator, registerValidationChecks } from './vmsc-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type VmscAddedServices = {
    validation: {
        VmscValidator: VmscValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type VmscServices = LangiumServices & VmscAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const VmscModule: Module<VmscServices, PartialLangiumServices & VmscAddedServices> = {
    validation: {
        VmscValidator: () => new VmscValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createVmscServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Vmsc: VmscServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        VmscGeneratedSharedModule
    );
    const Vmsc = inject(
        createDefaultModule({ shared }),
        VmscGeneratedModule,
        VmscModule
    );
    shared.ServiceRegistry.register(Vmsc);
    registerValidationChecks(Vmsc);
    return { shared, Vmsc };
}
