<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Vmsc" nsURI="http://www.Vmsc.gen" nsPrefix="Vmsc">
  <eClassifiers xsi:type="ecore:EClass" name="VEnum" eSuperTypes="#//VDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="VNamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VDatatype" eSuperTypes="#//VStructuralComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsSerializable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VPackage" eSuperTypes="#//VStructuralComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VComponents" upperBound="-1"
        eType="#//VStructuralComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VClass" eSuperTypes="#//VStructuralComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VSuperType" upperBound="-1"
        eType="#//VClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VStructural_features" upperBound="-1"
        eType="#//VStructuralFeatures" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VAttribute" eSuperTypes="#//VStructuralFeatures">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VType" eType="#//VType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VReference" eSuperTypes="#//VStructuralFeatures">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsContainer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsContainment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VType" eType="#//VClass"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VStructuralFeatures" abstract="true"
      eSuperTypes="#//VNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsChangeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsTransient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsUnsettable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsVolatile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VStructuralComponent" abstract="true"
      eSuperTypes="#//VNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VString" eSuperTypes="#//VType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VInt" eSuperTypes="#//VType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VFloat" eSuperTypes="#//VType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VType" abstract="true"/>
</ecore:EPackage>
