/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.vmsc.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.vmsc.ui.internal.VmscActivator;

public class VmscUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VmscActivator.getInstance().getInjector("org.xtext.example.vmsc.Vmsc");
	}

}
