/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.vmsc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.vmsc.VmscRuntimeModule;
import org.xtext.example.vmsc.VmscStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VmscIdeSetup extends VmscStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VmscRuntimeModule(), new VmscIdeModule()));
	}
	
}
