/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.vmsc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VmscUiModule extends AbstractVmscUiModule {

	public VmscUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
