/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.vmsc.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class VmscGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class VPackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VPackage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVPackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Alternatives cAlternatives_7 = (Alternatives)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cAlternatives_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_1 = (Keyword)cAlternatives_7.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cVPrefixKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cVPrefixAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cVPrefixEStringParserRuleCall_8_2_0 = (RuleCall)cVPrefixAssignment_8_2.eContents().get(0);
		private final Keyword cCommaKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cVUriKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cVUriAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cVUriEStringParserRuleCall_9_2_0 = (RuleCall)cVUriAssignment_9_2.eContents().get(0);
		private final Keyword cCommaKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cVComponentsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cColonKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Assignment cVComponentsAssignment_10_4 = (Assignment)cGroup_10.eContents().get(4);
		private final RuleCall cVComponentsVStructuralComponentParserRuleCall_10_4_0 = (RuleCall)cVComponentsAssignment_10_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_5 = (Keyword)cGroup_10.eContents().get(5);
		private final Group cGroup_10_6 = (Group)cGroup_10.eContents().get(6);
		private final Keyword cCommaKeyword_10_6_0 = (Keyword)cGroup_10_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_6_1 = (Keyword)cGroup_10_6.eContents().get(1);
		private final Assignment cVComponentsAssignment_10_6_2 = (Assignment)cGroup_10_6.eContents().get(2);
		private final RuleCall cVComponentsVStructuralComponentParserRuleCall_10_6_2_0 = (RuleCall)cVComponentsAssignment_10_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_6_3 = (Keyword)cGroup_10_6.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_10_7 = (Keyword)cGroup_10.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//VPackage returns VPackage:
		//    {VPackage}
		//    'VPackage' ':'
		//    '{'
		//    'name' ':' name=EString (',' | '}')
		//        ('VPrefix' ':' VPrefix=EString ',')
		//        ('VUri' ':' VUri=EString ',')
		//        ('VComponents' ':' '[' '{' VComponents+=VStructuralComponent '}' ( ',' '{' VComponents+=VStructuralComponent '}')* ']' )?
		//    '}'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{VPackage}
		//'VPackage' ':'
		//'{'
		//'name' ':' name=EString (',' | '}')
		//    ('VPrefix' ':' VPrefix=EString ',')
		//    ('VUri' ':' VUri=EString ',')
		//    ('VComponents' ':' '[' '{' VComponents+=VStructuralComponent '}' ( ',' '{' VComponents+=VStructuralComponent '}')* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VPackage}
		public Action getVPackageAction_0() { return cVPackageAction_0; }
		
		//'VPackage'
		public Keyword getVPackageKeyword_1() { return cVPackageKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//(',' | '}')
		public Alternatives getAlternatives_7() { return cAlternatives_7; }
		
		//','
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_1() { return cRightCurlyBracketKeyword_7_1; }
		
		//('VPrefix' ':' VPrefix=EString ',')
		public Group getGroup_8() { return cGroup_8; }
		
		//'VPrefix'
		public Keyword getVPrefixKeyword_8_0() { return cVPrefixKeyword_8_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//VPrefix=EString
		public Assignment getVPrefixAssignment_8_2() { return cVPrefixAssignment_8_2; }
		
		//EString
		public RuleCall getVPrefixEStringParserRuleCall_8_2_0() { return cVPrefixEStringParserRuleCall_8_2_0; }
		
		//','
		public Keyword getCommaKeyword_8_3() { return cCommaKeyword_8_3; }
		
		//('VUri' ':' VUri=EString ',')
		public Group getGroup_9() { return cGroup_9; }
		
		//'VUri'
		public Keyword getVUriKeyword_9_0() { return cVUriKeyword_9_0; }
		
		//':'
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }
		
		//VUri=EString
		public Assignment getVUriAssignment_9_2() { return cVUriAssignment_9_2; }
		
		//EString
		public RuleCall getVUriEStringParserRuleCall_9_2_0() { return cVUriEStringParserRuleCall_9_2_0; }
		
		//','
		public Keyword getCommaKeyword_9_3() { return cCommaKeyword_9_3; }
		
		//('VComponents' ':' '[' '{' VComponents+=VStructuralComponent '}' ( ',' '{' VComponents+=VStructuralComponent '}')* ']' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'VComponents'
		public Keyword getVComponentsKeyword_10_0() { return cVComponentsKeyword_10_0; }
		
		//':'
		public Keyword getColonKeyword_10_1() { return cColonKeyword_10_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_10_2() { return cLeftSquareBracketKeyword_10_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_3() { return cLeftCurlyBracketKeyword_10_3; }
		
		//VComponents+=VStructuralComponent
		public Assignment getVComponentsAssignment_10_4() { return cVComponentsAssignment_10_4; }
		
		//VStructuralComponent
		public RuleCall getVComponentsVStructuralComponentParserRuleCall_10_4_0() { return cVComponentsVStructuralComponentParserRuleCall_10_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_5() { return cRightCurlyBracketKeyword_10_5; }
		
		//( ',' '{' VComponents+=VStructuralComponent '}')*
		public Group getGroup_10_6() { return cGroup_10_6; }
		
		//','
		public Keyword getCommaKeyword_10_6_0() { return cCommaKeyword_10_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_6_1() { return cLeftCurlyBracketKeyword_10_6_1; }
		
		//VComponents+=VStructuralComponent
		public Assignment getVComponentsAssignment_10_6_2() { return cVComponentsAssignment_10_6_2; }
		
		//VStructuralComponent
		public RuleCall getVComponentsVStructuralComponentParserRuleCall_10_6_2_0() { return cVComponentsVStructuralComponentParserRuleCall_10_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_6_3() { return cRightCurlyBracketKeyword_10_6_3; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10_7() { return cRightSquareBracketKeyword_10_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class VStructuralComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VStructuralComponent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVEnumParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVDatatype_ImplParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVPackageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cVClassParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//VStructuralComponent returns VStructuralComponent:
		//    VEnum | VDatatype_Impl | VPackage | VClass;
		@Override public ParserRule getRule() { return rule; }
		
		//VEnum | VDatatype_Impl | VPackage | VClass
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VEnum
		public RuleCall getVEnumParserRuleCall_0() { return cVEnumParserRuleCall_0; }
		
		//VDatatype_Impl
		public RuleCall getVDatatype_ImplParserRuleCall_1() { return cVDatatype_ImplParserRuleCall_1; }
		
		//VPackage
		public RuleCall getVPackageParserRuleCall_2() { return cVPackageParserRuleCall_2; }
		
		//VClass
		public RuleCall getVClassParserRuleCall_3() { return cVClassParserRuleCall_3; }
	}
	public class VStructuralFeaturesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VStructuralFeatures");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVAttributeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVReferenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//VStructuralFeatures returns VStructuralFeatures:
		//    VAttribute | VReference;
		@Override public ParserRule getRule() { return rule; }
		
		//VAttribute | VReference
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VAttribute
		public RuleCall getVAttributeParserRuleCall_0() { return cVAttributeParserRuleCall_0; }
		
		//VReference
		public RuleCall getVReferenceParserRuleCall_1() { return cVReferenceParserRuleCall_1; }
	}
	public class VTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVStringParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVIntParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVFloatParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//VType returns VType:
		//    VString | VInt | VFloat;
		@Override public ParserRule getRule() { return rule; }
		
		//VString | VInt | VFloat
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VString
		public RuleCall getVStringParserRuleCall_0() { return cVStringParserRuleCall_0; }
		
		//VInt
		public RuleCall getVIntParserRuleCall_1() { return cVIntParserRuleCall_1; }
		
		//VFloat
		public RuleCall getVFloatParserRuleCall_2() { return cVFloatParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class VEnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VEnum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVEnumAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVEnumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cIsSerializableAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final Keyword cIsSerializableIsSerializableKeyword_8_0_0 = (Keyword)cIsSerializableAssignment_8_0.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cTrueKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Keyword cCommaKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//VEnum returns VEnum:
		//    {VEnum}
		//    'VEnum' ':'
		//    '{'
		//    'name' ':' name=EString ','
		//    (IsSerializable?='IsSerializable' ':' 'True' ',')?
		//    '}'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{VEnum}
		//'VEnum' ':'
		//'{'
		//'name' ':' name=EString ','
		//(IsSerializable?='IsSerializable' ':' 'True' ',')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VEnum}
		public Action getVEnumAction_0() { return cVEnumAction_0; }
		
		//'VEnum'
		public Keyword getVEnumKeyword_1() { return cVEnumKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//(IsSerializable?='IsSerializable' ':' 'True' ',')?
		public Group getGroup_8() { return cGroup_8; }
		
		//IsSerializable?='IsSerializable'
		public Assignment getIsSerializableAssignment_8_0() { return cIsSerializableAssignment_8_0; }
		
		//'IsSerializable'
		public Keyword getIsSerializableIsSerializableKeyword_8_0_0() { return cIsSerializableIsSerializableKeyword_8_0_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//'True'
		public Keyword getTrueKeyword_8_2() { return cTrueKeyword_8_2; }
		
		//','
		public Keyword getCommaKeyword_8_3() { return cCommaKeyword_8_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class VDatatype_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VDatatype_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVDatatypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVDatatypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cIsSerializableAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final Keyword cIsSerializableIsSerializableKeyword_8_0_0 = (Keyword)cIsSerializableAssignment_8_0.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cTrueKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Keyword cCommaKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//VDatatype_Impl returns VDatatype:
		//    {VDatatype}
		//    'VDatatype' ':'
		//    '{'
		//    'name' ':' name=EString ','
		//    (IsSerializable?='IsSerializable' ':' 'True' ',')?
		//    '}'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{VDatatype}
		//'VDatatype' ':'
		//'{'
		//'name' ':' name=EString ','
		//(IsSerializable?='IsSerializable' ':' 'True' ',')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VDatatype}
		public Action getVDatatypeAction_0() { return cVDatatypeAction_0; }
		
		//'VDatatype'
		public Keyword getVDatatypeKeyword_1() { return cVDatatypeKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//(IsSerializable?='IsSerializable' ':' 'True' ',')?
		public Group getGroup_8() { return cGroup_8; }
		
		//IsSerializable?='IsSerializable'
		public Assignment getIsSerializableAssignment_8_0() { return cIsSerializableAssignment_8_0; }
		
		//'IsSerializable'
		public Keyword getIsSerializableIsSerializableKeyword_8_0_0() { return cIsSerializableIsSerializableKeyword_8_0_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//'True'
		public Keyword getTrueKeyword_8_2() { return cTrueKeyword_8_2; }
		
		//','
		public Keyword getCommaKeyword_8_3() { return cCommaKeyword_8_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class VClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cVStructuralFeaturesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Assignment cVStructural_featuresAssignment_8_4 = (Assignment)cGroup_8.eContents().get(4);
		private final RuleCall cVStructural_featuresVStructuralFeaturesParserRuleCall_8_4_0 = (RuleCall)cVStructural_featuresAssignment_8_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_5 = (Keyword)cGroup_8.eContents().get(5);
		private final Group cGroup_8_6 = (Group)cGroup_8.eContents().get(6);
		private final Keyword cCommaKeyword_8_6_0 = (Keyword)cGroup_8_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_6_1 = (Keyword)cGroup_8_6.eContents().get(1);
		private final Assignment cVStructural_featuresAssignment_8_6_2 = (Assignment)cGroup_8_6.eContents().get(2);
		private final RuleCall cVStructural_featuresVStructuralFeaturesParserRuleCall_8_6_2_0 = (RuleCall)cVStructural_featuresAssignment_8_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_6_3 = (Keyword)cGroup_8_6.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_8_7 = (Keyword)cGroup_8.eContents().get(7);
		private final Keyword cCommaKeyword_8_8 = (Keyword)cGroup_8.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cVSuperTypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Assignment cVSuperTypeAssignment_9_3 = (Assignment)cGroup_9.eContents().get(3);
		private final CrossReference cVSuperTypeVClassCrossReference_9_3_0 = (CrossReference)cVSuperTypeAssignment_9_3.eContents().get(0);
		private final RuleCall cVSuperTypeVClassEStringParserRuleCall_9_3_0_1 = (RuleCall)cVSuperTypeVClassCrossReference_9_3_0.eContents().get(1);
		private final Group cGroup_9_4 = (Group)cGroup_9.eContents().get(4);
		private final Keyword cCommaKeyword_9_4_0 = (Keyword)cGroup_9_4.eContents().get(0);
		private final Assignment cVSuperTypeAssignment_9_4_1 = (Assignment)cGroup_9_4.eContents().get(1);
		private final CrossReference cVSuperTypeVClassCrossReference_9_4_1_0 = (CrossReference)cVSuperTypeAssignment_9_4_1.eContents().get(0);
		private final RuleCall cVSuperTypeVClassEStringParserRuleCall_9_4_1_0_1 = (RuleCall)cVSuperTypeVClassCrossReference_9_4_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_9_5 = (Keyword)cGroup_9.eContents().get(5);
		private final Keyword cCommaKeyword_9_6 = (Keyword)cGroup_9.eContents().get(6);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cIsAbstractAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final Keyword cIsAbstractIsAbstractKeyword_10_0_0 = (Keyword)cIsAbstractAssignment_10_0.eContents().get(0);
		private final Keyword cColonKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cTrueKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Keyword cCommaKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cIsInterfaceAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final Keyword cIsInterfaceIsInterfaceKeyword_11_0_0 = (Keyword)cIsInterfaceAssignment_11_0.eContents().get(0);
		private final Keyword cColonKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Keyword cTrueKeyword_11_2 = (Keyword)cGroup_11.eContents().get(2);
		private final Keyword cCommaKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//VClass returns VClass:
		//    {VClass}
		//    'VClass' ':'
		//    '{'
		//    'name' ':' name=EString ','
		//    ('VStructuralFeatures' ':' '[' '{' VStructural_features+=VStructuralFeatures '}' ( ',' '{' VStructural_features+=VStructuralFeatures '}')*  ']' ',')?
		//    ('VSuperType' ':' '['  VSuperType+=[VClass|EString] ( ',' VSuperType+=[VClass|EString])* ']' ',')?
		//    (IsAbstract?='IsAbstract' ':' 'True' ',')?
		//    (IsInterface?='IsInterface' ':' 'True' ',')?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VClass}
		//'VClass' ':'
		//'{'
		//'name' ':' name=EString ','
		//('VStructuralFeatures' ':' '[' '{' VStructural_features+=VStructuralFeatures '}' ( ',' '{' VStructural_features+=VStructuralFeatures '}')*  ']' ',')?
		//('VSuperType' ':' '['  VSuperType+=[VClass|EString] ( ',' VSuperType+=[VClass|EString])* ']' ',')?
		//(IsAbstract?='IsAbstract' ':' 'True' ',')?
		//(IsInterface?='IsInterface' ':' 'True' ',')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VClass}
		public Action getVClassAction_0() { return cVClassAction_0; }
		
		//'VClass'
		public Keyword getVClassKeyword_1() { return cVClassKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//('VStructuralFeatures' ':' '[' '{' VStructural_features+=VStructuralFeatures '}' ( ',' '{' VStructural_features+=VStructuralFeatures '}')*  ']' ',')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'VStructuralFeatures'
		public Keyword getVStructuralFeaturesKeyword_8_0() { return cVStructuralFeaturesKeyword_8_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8_2() { return cLeftSquareBracketKeyword_8_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_3() { return cLeftCurlyBracketKeyword_8_3; }
		
		//VStructural_features+=VStructuralFeatures
		public Assignment getVStructural_featuresAssignment_8_4() { return cVStructural_featuresAssignment_8_4; }
		
		//VStructuralFeatures
		public RuleCall getVStructural_featuresVStructuralFeaturesParserRuleCall_8_4_0() { return cVStructural_featuresVStructuralFeaturesParserRuleCall_8_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_5() { return cRightCurlyBracketKeyword_8_5; }
		
		//( ',' '{' VStructural_features+=VStructuralFeatures '}')*
		public Group getGroup_8_6() { return cGroup_8_6; }
		
		//','
		public Keyword getCommaKeyword_8_6_0() { return cCommaKeyword_8_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_6_1() { return cLeftCurlyBracketKeyword_8_6_1; }
		
		//VStructural_features+=VStructuralFeatures
		public Assignment getVStructural_featuresAssignment_8_6_2() { return cVStructural_featuresAssignment_8_6_2; }
		
		//VStructuralFeatures
		public RuleCall getVStructural_featuresVStructuralFeaturesParserRuleCall_8_6_2_0() { return cVStructural_featuresVStructuralFeaturesParserRuleCall_8_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_6_3() { return cRightCurlyBracketKeyword_8_6_3; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_8_7() { return cRightSquareBracketKeyword_8_7; }
		
		//','
		public Keyword getCommaKeyword_8_8() { return cCommaKeyword_8_8; }
		
		//('VSuperType' ':' '['  VSuperType+=[VClass|EString] ( ',' VSuperType+=[VClass|EString])* ']' ',')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'VSuperType'
		public Keyword getVSuperTypeKeyword_9_0() { return cVSuperTypeKeyword_9_0; }
		
		//':'
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_9_2() { return cLeftSquareBracketKeyword_9_2; }
		
		//VSuperType+=[VClass|EString]
		public Assignment getVSuperTypeAssignment_9_3() { return cVSuperTypeAssignment_9_3; }
		
		//[VClass|EString]
		public CrossReference getVSuperTypeVClassCrossReference_9_3_0() { return cVSuperTypeVClassCrossReference_9_3_0; }
		
		//EString
		public RuleCall getVSuperTypeVClassEStringParserRuleCall_9_3_0_1() { return cVSuperTypeVClassEStringParserRuleCall_9_3_0_1; }
		
		//( ',' VSuperType+=[VClass|EString])*
		public Group getGroup_9_4() { return cGroup_9_4; }
		
		//','
		public Keyword getCommaKeyword_9_4_0() { return cCommaKeyword_9_4_0; }
		
		//VSuperType+=[VClass|EString]
		public Assignment getVSuperTypeAssignment_9_4_1() { return cVSuperTypeAssignment_9_4_1; }
		
		//[VClass|EString]
		public CrossReference getVSuperTypeVClassCrossReference_9_4_1_0() { return cVSuperTypeVClassCrossReference_9_4_1_0; }
		
		//EString
		public RuleCall getVSuperTypeVClassEStringParserRuleCall_9_4_1_0_1() { return cVSuperTypeVClassEStringParserRuleCall_9_4_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9_5() { return cRightSquareBracketKeyword_9_5; }
		
		//','
		public Keyword getCommaKeyword_9_6() { return cCommaKeyword_9_6; }
		
		//(IsAbstract?='IsAbstract' ':' 'True' ',')?
		public Group getGroup_10() { return cGroup_10; }
		
		//IsAbstract?='IsAbstract'
		public Assignment getIsAbstractAssignment_10_0() { return cIsAbstractAssignment_10_0; }
		
		//'IsAbstract'
		public Keyword getIsAbstractIsAbstractKeyword_10_0_0() { return cIsAbstractIsAbstractKeyword_10_0_0; }
		
		//':'
		public Keyword getColonKeyword_10_1() { return cColonKeyword_10_1; }
		
		//'True'
		public Keyword getTrueKeyword_10_2() { return cTrueKeyword_10_2; }
		
		//','
		public Keyword getCommaKeyword_10_3() { return cCommaKeyword_10_3; }
		
		//(IsInterface?='IsInterface' ':' 'True' ',')?
		public Group getGroup_11() { return cGroup_11; }
		
		//IsInterface?='IsInterface'
		public Assignment getIsInterfaceAssignment_11_0() { return cIsInterfaceAssignment_11_0; }
		
		//'IsInterface'
		public Keyword getIsInterfaceIsInterfaceKeyword_11_0_0() { return cIsInterfaceIsInterfaceKeyword_11_0_0; }
		
		//':'
		public Keyword getColonKeyword_11_1() { return cColonKeyword_11_1; }
		
		//'True'
		public Keyword getTrueKeyword_11_2() { return cTrueKeyword_11_2; }
		
		//','
		public Keyword getCommaKeyword_11_3() { return cCommaKeyword_11_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class VAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVAttributeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVAttributeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIsChangeableAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cIsChangeableIsChangeableKeyword_8_0 = (Keyword)cIsChangeableAssignment_8.eContents().get(0);
		private final Assignment cIsOrderedAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final Keyword cIsOrderedIsOrderedKeyword_9_0 = (Keyword)cIsOrderedAssignment_9.eContents().get(0);
		private final Assignment cIsTransientAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final Keyword cIsTransientIsTransientKeyword_10_0 = (Keyword)cIsTransientAssignment_10.eContents().get(0);
		private final Assignment cIsUnsettableAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final Keyword cIsUnsettableIsUnsettableKeyword_11_0 = (Keyword)cIsUnsettableAssignment_11.eContents().get(0);
		private final Assignment cIsVolatileAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final Keyword cIsVolatileIsVolatileKeyword_12_0 = (Keyword)cIsVolatileAssignment_12.eContents().get(0);
		private final Assignment cIsDerivedAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final Keyword cIsDerivedIsDerivedKeyword_13_0 = (Keyword)cIsDerivedAssignment_13.eContents().get(0);
		private final Assignment cIsUniqueAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final Keyword cIsUniqueIsUniqueKeyword_14_0 = (Keyword)cIsUniqueAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cLowerBoundKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cColonKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cLowerBoundAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final RuleCall cLowerBoundEIntParserRuleCall_15_2_0 = (RuleCall)cLowerBoundAssignment_15_2.eContents().get(0);
		private final Keyword cCommaKeyword_15_3 = (Keyword)cGroup_15.eContents().get(3);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cUpperBoundKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cColonKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Assignment cUpperBoundAssignment_16_2 = (Assignment)cGroup_16.eContents().get(2);
		private final RuleCall cUpperBoundEIntParserRuleCall_16_2_0 = (RuleCall)cUpperBoundAssignment_16_2.eContents().get(0);
		private final Keyword cCommaKeyword_16_3 = (Keyword)cGroup_16.eContents().get(3);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cVTypeKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Keyword cColonKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Assignment cVTypeAssignment_17_2 = (Assignment)cGroup_17.eContents().get(2);
		private final RuleCall cVTypeVTypeParserRuleCall_17_2_0 = (RuleCall)cVTypeAssignment_17_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//VAttribute returns VAttribute:
		//    {VAttribute}
		//    'VAttribute' ':'
		//    '{'
		//    'name' ':' name=EString ','
		//    (IsChangeable?='IsChangeable')?
		//    (IsOrdered?='IsOrdered')?
		//    (IsTransient?='IsTransient')?
		//    (IsUnsettable?='IsUnsettable')?
		//    (IsVolatile?='IsVolatile')?
		//    (IsDerived?='IsDerived')?
		//    (IsUnique?='IsUnique')?
		//        ('LowerBound' ':' LowerBound=EInt ',')?
		//        ('UpperBound' ':' UpperBound=EInt ',')?
		//        ('VType' ':' VType=VType)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VAttribute}
		//'VAttribute' ':'
		//'{'
		//'name' ':' name=EString ','
		//(IsChangeable?='IsChangeable')?
		//(IsOrdered?='IsOrdered')?
		//(IsTransient?='IsTransient')?
		//(IsUnsettable?='IsUnsettable')?
		//(IsVolatile?='IsVolatile')?
		//(IsDerived?='IsDerived')?
		//(IsUnique?='IsUnique')?
		//    ('LowerBound' ':' LowerBound=EInt ',')?
		//    ('UpperBound' ':' UpperBound=EInt ',')?
		//    ('VType' ':' VType=VType)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VAttribute}
		public Action getVAttributeAction_0() { return cVAttributeAction_0; }
		
		//'VAttribute'
		public Keyword getVAttributeKeyword_1() { return cVAttributeKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//(IsChangeable?='IsChangeable')?
		public Assignment getIsChangeableAssignment_8() { return cIsChangeableAssignment_8; }
		
		//'IsChangeable'
		public Keyword getIsChangeableIsChangeableKeyword_8_0() { return cIsChangeableIsChangeableKeyword_8_0; }
		
		//(IsOrdered?='IsOrdered')?
		public Assignment getIsOrderedAssignment_9() { return cIsOrderedAssignment_9; }
		
		//'IsOrdered'
		public Keyword getIsOrderedIsOrderedKeyword_9_0() { return cIsOrderedIsOrderedKeyword_9_0; }
		
		//(IsTransient?='IsTransient')?
		public Assignment getIsTransientAssignment_10() { return cIsTransientAssignment_10; }
		
		//'IsTransient'
		public Keyword getIsTransientIsTransientKeyword_10_0() { return cIsTransientIsTransientKeyword_10_0; }
		
		//(IsUnsettable?='IsUnsettable')?
		public Assignment getIsUnsettableAssignment_11() { return cIsUnsettableAssignment_11; }
		
		//'IsUnsettable'
		public Keyword getIsUnsettableIsUnsettableKeyword_11_0() { return cIsUnsettableIsUnsettableKeyword_11_0; }
		
		//(IsVolatile?='IsVolatile')?
		public Assignment getIsVolatileAssignment_12() { return cIsVolatileAssignment_12; }
		
		//'IsVolatile'
		public Keyword getIsVolatileIsVolatileKeyword_12_0() { return cIsVolatileIsVolatileKeyword_12_0; }
		
		//(IsDerived?='IsDerived')?
		public Assignment getIsDerivedAssignment_13() { return cIsDerivedAssignment_13; }
		
		//'IsDerived'
		public Keyword getIsDerivedIsDerivedKeyword_13_0() { return cIsDerivedIsDerivedKeyword_13_0; }
		
		//(IsUnique?='IsUnique')?
		public Assignment getIsUniqueAssignment_14() { return cIsUniqueAssignment_14; }
		
		//'IsUnique'
		public Keyword getIsUniqueIsUniqueKeyword_14_0() { return cIsUniqueIsUniqueKeyword_14_0; }
		
		//('LowerBound' ':' LowerBound=EInt ',')?
		public Group getGroup_15() { return cGroup_15; }
		
		//'LowerBound'
		public Keyword getLowerBoundKeyword_15_0() { return cLowerBoundKeyword_15_0; }
		
		//':'
		public Keyword getColonKeyword_15_1() { return cColonKeyword_15_1; }
		
		//LowerBound=EInt
		public Assignment getLowerBoundAssignment_15_2() { return cLowerBoundAssignment_15_2; }
		
		//EInt
		public RuleCall getLowerBoundEIntParserRuleCall_15_2_0() { return cLowerBoundEIntParserRuleCall_15_2_0; }
		
		//','
		public Keyword getCommaKeyword_15_3() { return cCommaKeyword_15_3; }
		
		//('UpperBound' ':' UpperBound=EInt ',')?
		public Group getGroup_16() { return cGroup_16; }
		
		//'UpperBound'
		public Keyword getUpperBoundKeyword_16_0() { return cUpperBoundKeyword_16_0; }
		
		//':'
		public Keyword getColonKeyword_16_1() { return cColonKeyword_16_1; }
		
		//UpperBound=EInt
		public Assignment getUpperBoundAssignment_16_2() { return cUpperBoundAssignment_16_2; }
		
		//EInt
		public RuleCall getUpperBoundEIntParserRuleCall_16_2_0() { return cUpperBoundEIntParserRuleCall_16_2_0; }
		
		//','
		public Keyword getCommaKeyword_16_3() { return cCommaKeyword_16_3; }
		
		//('VType' ':' VType=VType)?
		public Group getGroup_17() { return cGroup_17; }
		
		//'VType'
		public Keyword getVTypeKeyword_17_0() { return cVTypeKeyword_17_0; }
		
		//':'
		public Keyword getColonKeyword_17_1() { return cColonKeyword_17_1; }
		
		//VType=VType
		public Assignment getVTypeAssignment_17_2() { return cVTypeAssignment_17_2; }
		
		//VType
		public RuleCall getVTypeVTypeParserRuleCall_17_2_0() { return cVTypeVTypeParserRuleCall_17_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class VReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VReference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVReferenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVReferenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cIsChangeableAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final Keyword cIsChangeableIsChangeableKeyword_8_0_0 = (Keyword)cIsChangeableAssignment_8_0.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cTrueKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Keyword cCommaKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Assignment cIsOrderedAssignment_9_0 = (Assignment)cGroup_9.eContents().get(0);
		private final Keyword cIsOrderedIsOrderedKeyword_9_0_0 = (Keyword)cIsOrderedAssignment_9_0.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Keyword cTrueKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Keyword cCommaKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cIsTransientAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final Keyword cIsTransientIsTransientKeyword_10_0_0 = (Keyword)cIsTransientAssignment_10_0.eContents().get(0);
		private final Keyword cColonKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cTrueKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Keyword cCommaKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cIsUnsettableAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final Keyword cIsUnsettableIsUnsettableKeyword_11_0_0 = (Keyword)cIsUnsettableAssignment_11_0.eContents().get(0);
		private final Keyword cColonKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Keyword cTrueKeyword_11_2 = (Keyword)cGroup_11.eContents().get(2);
		private final Keyword cCommaKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Assignment cIsVolatileAssignment_12_0 = (Assignment)cGroup_12.eContents().get(0);
		private final Keyword cIsVolatileIsVolatileKeyword_12_0_0 = (Keyword)cIsVolatileAssignment_12_0.eContents().get(0);
		private final Keyword cColonKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Keyword cTrueKeyword_12_2 = (Keyword)cGroup_12.eContents().get(2);
		private final Keyword cCommaKeyword_12_3 = (Keyword)cGroup_12.eContents().get(3);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Assignment cIsDerivedAssignment_13_0 = (Assignment)cGroup_13.eContents().get(0);
		private final Keyword cIsDerivedIsDerivedKeyword_13_0_0 = (Keyword)cIsDerivedAssignment_13_0.eContents().get(0);
		private final Keyword cColonKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Keyword cTrueKeyword_13_2 = (Keyword)cGroup_13.eContents().get(2);
		private final Keyword cCommaKeyword_13_3 = (Keyword)cGroup_13.eContents().get(3);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Assignment cIsUniqueAssignment_14_0 = (Assignment)cGroup_14.eContents().get(0);
		private final Keyword cIsUniqueIsUniqueKeyword_14_0_0 = (Keyword)cIsUniqueAssignment_14_0.eContents().get(0);
		private final Keyword cColonKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Keyword cTrueKeyword_14_2 = (Keyword)cGroup_14.eContents().get(2);
		private final Keyword cCommaKeyword_14_3 = (Keyword)cGroup_14.eContents().get(3);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Assignment cIsContainerAssignment_15_0 = (Assignment)cGroup_15.eContents().get(0);
		private final Keyword cIsContainerIsContainerKeyword_15_0_0 = (Keyword)cIsContainerAssignment_15_0.eContents().get(0);
		private final Keyword cColonKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Keyword cTrueKeyword_15_2 = (Keyword)cGroup_15.eContents().get(2);
		private final Keyword cCommaKeyword_15_3 = (Keyword)cGroup_15.eContents().get(3);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Assignment cIsContainmentAssignment_16_0 = (Assignment)cGroup_16.eContents().get(0);
		private final Keyword cIsContainmentIsContainmentKeyword_16_0_0 = (Keyword)cIsContainmentAssignment_16_0.eContents().get(0);
		private final Keyword cColonKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Keyword cTrueKeyword_16_2 = (Keyword)cGroup_16.eContents().get(2);
		private final Keyword cCommaKeyword_16_3 = (Keyword)cGroup_16.eContents().get(3);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cLowerBoundKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Keyword cColonKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Assignment cLowerBoundAssignment_17_2 = (Assignment)cGroup_17.eContents().get(2);
		private final RuleCall cLowerBoundEIntParserRuleCall_17_2_0 = (RuleCall)cLowerBoundAssignment_17_2.eContents().get(0);
		private final Keyword cCommaKeyword_17_3 = (Keyword)cGroup_17.eContents().get(3);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cUpperBoundKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Keyword cColonKeyword_18_1 = (Keyword)cGroup_18.eContents().get(1);
		private final Assignment cUpperBoundAssignment_18_2 = (Assignment)cGroup_18.eContents().get(2);
		private final RuleCall cUpperBoundEIntParserRuleCall_18_2_0 = (RuleCall)cUpperBoundAssignment_18_2.eContents().get(0);
		private final Keyword cCommaKeyword_18_3 = (Keyword)cGroup_18.eContents().get(3);
		private final Group cGroup_19 = (Group)cGroup.eContents().get(19);
		private final Keyword cVTypeKeyword_19_0 = (Keyword)cGroup_19.eContents().get(0);
		private final Keyword cColonKeyword_19_1 = (Keyword)cGroup_19.eContents().get(1);
		private final Assignment cVTypeAssignment_19_2 = (Assignment)cGroup_19.eContents().get(2);
		private final RuleCall cVTypeVClassParserRuleCall_19_2_0 = (RuleCall)cVTypeAssignment_19_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		
		//VReference returns VReference:
		//    {VReference}
		//    'VReference' ':'
		//    '{'
		//    'name' ':' name=EString ','
		//    (IsChangeable?='IsChangeable' ':' 'True' ',')?
		//    (IsOrdered?='IsOrdered' ':' 'True' ',')?
		//    (IsTransient?='IsTransient' ':' 'True' ',')?
		//    (IsUnsettable?='IsUnsettable' ':' 'True' ',')?
		//    (IsVolatile?='IsVolatile' ':' 'True' ',')?
		//    (IsDerived?='IsDerived' ':' 'True' ',')?
		//    (IsUnique?='IsUnique' ':' 'True' ',')?
		//    (IsContainer?='IsContainer' ':' 'True' ',')?
		//    (IsContainment?='IsContainment' ':' 'True' ',')?
		//        ('LowerBound' ':' LowerBound=EInt ',')?
		//        ('UpperBound' ':' UpperBound=EInt ',')?
		//        ('VType' ':' VType=VClass)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VReference}
		//'VReference' ':'
		//'{'
		//'name' ':' name=EString ','
		//(IsChangeable?='IsChangeable' ':' 'True' ',')?
		//(IsOrdered?='IsOrdered' ':' 'True' ',')?
		//(IsTransient?='IsTransient' ':' 'True' ',')?
		//(IsUnsettable?='IsUnsettable' ':' 'True' ',')?
		//(IsVolatile?='IsVolatile' ':' 'True' ',')?
		//(IsDerived?='IsDerived' ':' 'True' ',')?
		//(IsUnique?='IsUnique' ':' 'True' ',')?
		//(IsContainer?='IsContainer' ':' 'True' ',')?
		//(IsContainment?='IsContainment' ':' 'True' ',')?
		//    ('LowerBound' ':' LowerBound=EInt ',')?
		//    ('UpperBound' ':' UpperBound=EInt ',')?
		//    ('VType' ':' VType=VClass)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VReference}
		public Action getVReferenceAction_0() { return cVReferenceAction_0; }
		
		//'VReference'
		public Keyword getVReferenceKeyword_1() { return cVReferenceKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//(IsChangeable?='IsChangeable' ':' 'True' ',')?
		public Group getGroup_8() { return cGroup_8; }
		
		//IsChangeable?='IsChangeable'
		public Assignment getIsChangeableAssignment_8_0() { return cIsChangeableAssignment_8_0; }
		
		//'IsChangeable'
		public Keyword getIsChangeableIsChangeableKeyword_8_0_0() { return cIsChangeableIsChangeableKeyword_8_0_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//'True'
		public Keyword getTrueKeyword_8_2() { return cTrueKeyword_8_2; }
		
		//','
		public Keyword getCommaKeyword_8_3() { return cCommaKeyword_8_3; }
		
		//(IsOrdered?='IsOrdered' ':' 'True' ',')?
		public Group getGroup_9() { return cGroup_9; }
		
		//IsOrdered?='IsOrdered'
		public Assignment getIsOrderedAssignment_9_0() { return cIsOrderedAssignment_9_0; }
		
		//'IsOrdered'
		public Keyword getIsOrderedIsOrderedKeyword_9_0_0() { return cIsOrderedIsOrderedKeyword_9_0_0; }
		
		//':'
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }
		
		//'True'
		public Keyword getTrueKeyword_9_2() { return cTrueKeyword_9_2; }
		
		//','
		public Keyword getCommaKeyword_9_3() { return cCommaKeyword_9_3; }
		
		//(IsTransient?='IsTransient' ':' 'True' ',')?
		public Group getGroup_10() { return cGroup_10; }
		
		//IsTransient?='IsTransient'
		public Assignment getIsTransientAssignment_10_0() { return cIsTransientAssignment_10_0; }
		
		//'IsTransient'
		public Keyword getIsTransientIsTransientKeyword_10_0_0() { return cIsTransientIsTransientKeyword_10_0_0; }
		
		//':'
		public Keyword getColonKeyword_10_1() { return cColonKeyword_10_1; }
		
		//'True'
		public Keyword getTrueKeyword_10_2() { return cTrueKeyword_10_2; }
		
		//','
		public Keyword getCommaKeyword_10_3() { return cCommaKeyword_10_3; }
		
		//(IsUnsettable?='IsUnsettable' ':' 'True' ',')?
		public Group getGroup_11() { return cGroup_11; }
		
		//IsUnsettable?='IsUnsettable'
		public Assignment getIsUnsettableAssignment_11_0() { return cIsUnsettableAssignment_11_0; }
		
		//'IsUnsettable'
		public Keyword getIsUnsettableIsUnsettableKeyword_11_0_0() { return cIsUnsettableIsUnsettableKeyword_11_0_0; }
		
		//':'
		public Keyword getColonKeyword_11_1() { return cColonKeyword_11_1; }
		
		//'True'
		public Keyword getTrueKeyword_11_2() { return cTrueKeyword_11_2; }
		
		//','
		public Keyword getCommaKeyword_11_3() { return cCommaKeyword_11_3; }
		
		//(IsVolatile?='IsVolatile' ':' 'True' ',')?
		public Group getGroup_12() { return cGroup_12; }
		
		//IsVolatile?='IsVolatile'
		public Assignment getIsVolatileAssignment_12_0() { return cIsVolatileAssignment_12_0; }
		
		//'IsVolatile'
		public Keyword getIsVolatileIsVolatileKeyword_12_0_0() { return cIsVolatileIsVolatileKeyword_12_0_0; }
		
		//':'
		public Keyword getColonKeyword_12_1() { return cColonKeyword_12_1; }
		
		//'True'
		public Keyword getTrueKeyword_12_2() { return cTrueKeyword_12_2; }
		
		//','
		public Keyword getCommaKeyword_12_3() { return cCommaKeyword_12_3; }
		
		//(IsDerived?='IsDerived' ':' 'True' ',')?
		public Group getGroup_13() { return cGroup_13; }
		
		//IsDerived?='IsDerived'
		public Assignment getIsDerivedAssignment_13_0() { return cIsDerivedAssignment_13_0; }
		
		//'IsDerived'
		public Keyword getIsDerivedIsDerivedKeyword_13_0_0() { return cIsDerivedIsDerivedKeyword_13_0_0; }
		
		//':'
		public Keyword getColonKeyword_13_1() { return cColonKeyword_13_1; }
		
		//'True'
		public Keyword getTrueKeyword_13_2() { return cTrueKeyword_13_2; }
		
		//','
		public Keyword getCommaKeyword_13_3() { return cCommaKeyword_13_3; }
		
		//(IsUnique?='IsUnique' ':' 'True' ',')?
		public Group getGroup_14() { return cGroup_14; }
		
		//IsUnique?='IsUnique'
		public Assignment getIsUniqueAssignment_14_0() { return cIsUniqueAssignment_14_0; }
		
		//'IsUnique'
		public Keyword getIsUniqueIsUniqueKeyword_14_0_0() { return cIsUniqueIsUniqueKeyword_14_0_0; }
		
		//':'
		public Keyword getColonKeyword_14_1() { return cColonKeyword_14_1; }
		
		//'True'
		public Keyword getTrueKeyword_14_2() { return cTrueKeyword_14_2; }
		
		//','
		public Keyword getCommaKeyword_14_3() { return cCommaKeyword_14_3; }
		
		//(IsContainer?='IsContainer' ':' 'True' ',')?
		public Group getGroup_15() { return cGroup_15; }
		
		//IsContainer?='IsContainer'
		public Assignment getIsContainerAssignment_15_0() { return cIsContainerAssignment_15_0; }
		
		//'IsContainer'
		public Keyword getIsContainerIsContainerKeyword_15_0_0() { return cIsContainerIsContainerKeyword_15_0_0; }
		
		//':'
		public Keyword getColonKeyword_15_1() { return cColonKeyword_15_1; }
		
		//'True'
		public Keyword getTrueKeyword_15_2() { return cTrueKeyword_15_2; }
		
		//','
		public Keyword getCommaKeyword_15_3() { return cCommaKeyword_15_3; }
		
		//(IsContainment?='IsContainment' ':' 'True' ',')?
		public Group getGroup_16() { return cGroup_16; }
		
		//IsContainment?='IsContainment'
		public Assignment getIsContainmentAssignment_16_0() { return cIsContainmentAssignment_16_0; }
		
		//'IsContainment'
		public Keyword getIsContainmentIsContainmentKeyword_16_0_0() { return cIsContainmentIsContainmentKeyword_16_0_0; }
		
		//':'
		public Keyword getColonKeyword_16_1() { return cColonKeyword_16_1; }
		
		//'True'
		public Keyword getTrueKeyword_16_2() { return cTrueKeyword_16_2; }
		
		//','
		public Keyword getCommaKeyword_16_3() { return cCommaKeyword_16_3; }
		
		//('LowerBound' ':' LowerBound=EInt ',')?
		public Group getGroup_17() { return cGroup_17; }
		
		//'LowerBound'
		public Keyword getLowerBoundKeyword_17_0() { return cLowerBoundKeyword_17_0; }
		
		//':'
		public Keyword getColonKeyword_17_1() { return cColonKeyword_17_1; }
		
		//LowerBound=EInt
		public Assignment getLowerBoundAssignment_17_2() { return cLowerBoundAssignment_17_2; }
		
		//EInt
		public RuleCall getLowerBoundEIntParserRuleCall_17_2_0() { return cLowerBoundEIntParserRuleCall_17_2_0; }
		
		//','
		public Keyword getCommaKeyword_17_3() { return cCommaKeyword_17_3; }
		
		//('UpperBound' ':' UpperBound=EInt ',')?
		public Group getGroup_18() { return cGroup_18; }
		
		//'UpperBound'
		public Keyword getUpperBoundKeyword_18_0() { return cUpperBoundKeyword_18_0; }
		
		//':'
		public Keyword getColonKeyword_18_1() { return cColonKeyword_18_1; }
		
		//UpperBound=EInt
		public Assignment getUpperBoundAssignment_18_2() { return cUpperBoundAssignment_18_2; }
		
		//EInt
		public RuleCall getUpperBoundEIntParserRuleCall_18_2_0() { return cUpperBoundEIntParserRuleCall_18_2_0; }
		
		//','
		public Keyword getCommaKeyword_18_3() { return cCommaKeyword_18_3; }
		
		//('VType' ':' VType=VClass)?
		public Group getGroup_19() { return cGroup_19; }
		
		//'VType'
		public Keyword getVTypeKeyword_19_0() { return cVTypeKeyword_19_0; }
		
		//':'
		public Keyword getColonKeyword_19_1() { return cColonKeyword_19_1; }
		
		//VType=VClass
		public Assignment getVTypeAssignment_19_2() { return cVTypeAssignment_19_2; }
		
		//VClass
		public RuleCall getVTypeVClassParserRuleCall_19_2_0() { return cVTypeVClassParserRuleCall_19_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_20() { return cRightCurlyBracketKeyword_20; }
	}
	public class VStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VString");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVStringKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVContentKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cVContentAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVContentEStringParserRuleCall_5_0 = (RuleCall)cVContentAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//VString returns VString:
		//    {VString}
		//    'VString'
		//    ','
		//    'VContent' ':' VContent=EString
		//    ','?;
		@Override public ParserRule getRule() { return rule; }
		
		//{VString}
		//'VString'
		//','
		//'VContent' ':' VContent=EString
		//','?
		public Group getGroup() { return cGroup; }
		
		//{VString}
		public Action getVStringAction_0() { return cVStringAction_0; }
		
		//'VString'
		public Keyword getVStringKeyword_1() { return cVStringKeyword_1; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//'VContent'
		public Keyword getVContentKeyword_3() { return cVContentKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//VContent=EString
		public Assignment getVContentAssignment_5() { return cVContentAssignment_5; }
		
		//EString
		public RuleCall getVContentEStringParserRuleCall_5_0() { return cVContentEStringParserRuleCall_5_0; }
		
		//','?
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
	}
	public class VIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVIntAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVIntKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVContentKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cVContentAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVContentEIntParserRuleCall_5_0 = (RuleCall)cVContentAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//VInt returns VInt:
		//    {VInt}
		//    'VInt'
		//    ','
		//    'VContent' ':' VContent=EInt
		//    ','?;
		@Override public ParserRule getRule() { return rule; }
		
		//{VInt}
		//'VInt'
		//','
		//'VContent' ':' VContent=EInt
		//','?
		public Group getGroup() { return cGroup; }
		
		//{VInt}
		public Action getVIntAction_0() { return cVIntAction_0; }
		
		//'VInt'
		public Keyword getVIntKeyword_1() { return cVIntKeyword_1; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//'VContent'
		public Keyword getVContentKeyword_3() { return cVContentKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//VContent=EInt
		public Assignment getVContentAssignment_5() { return cVContentAssignment_5; }
		
		//EInt
		public RuleCall getVContentEIntParserRuleCall_5_0() { return cVContentEIntParserRuleCall_5_0; }
		
		//','?
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
	}
	public class VFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.VFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVFloatAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVFloatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVContentKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cVContentAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVContentEFloatParserRuleCall_5_0 = (RuleCall)cVContentAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//VFloat returns VFloat:
		//    {VFloat}
		//    'VFloat'
		//    ','
		//    'VContent' ':' VContent=EFloat
		//    ','?;
		@Override public ParserRule getRule() { return rule; }
		
		//{VFloat}
		//'VFloat'
		//','
		//'VContent' ':' VContent=EFloat
		//','?
		public Group getGroup() { return cGroup; }
		
		//{VFloat}
		public Action getVFloatAction_0() { return cVFloatAction_0; }
		
		//'VFloat'
		public Keyword getVFloatKeyword_1() { return cVFloatKeyword_1; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//'VContent'
		public Keyword getVContentKeyword_3() { return cVContentKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//VContent=EFloat
		public Assignment getVContentAssignment_5() { return cVContentAssignment_5; }
		
		//EFloat
		public RuleCall getVContentEFloatParserRuleCall_5_0() { return cVContentEFloatParserRuleCall_5_0; }
		
		//','?
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.vmsc.Vmsc.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	
	private final VPackageElements pVPackage;
	private final VStructuralComponentElements pVStructuralComponent;
	private final VStructuralFeaturesElements pVStructuralFeatures;
	private final VTypeElements pVType;
	private final EStringElements pEString;
	private final VEnumElements pVEnum;
	private final VDatatype_ImplElements pVDatatype_Impl;
	private final VClassElements pVClass;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final VAttributeElements pVAttribute;
	private final VReferenceElements pVReference;
	private final VStringElements pVString;
	private final VIntElements pVInt;
	private final VFloatElements pVFloat;
	private final EFloatElements pEFloat;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public VmscGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pVPackage = new VPackageElements();
		this.pVStructuralComponent = new VStructuralComponentElements();
		this.pVStructuralFeatures = new VStructuralFeaturesElements();
		this.pVType = new VTypeElements();
		this.pEString = new EStringElements();
		this.pVEnum = new VEnumElements();
		this.pVDatatype_Impl = new VDatatype_ImplElements();
		this.pVClass = new VClassElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pVAttribute = new VAttributeElements();
		this.pVReference = new VReferenceElements();
		this.pVString = new VStringElements();
		this.pVInt = new VIntElements();
		this.pVFloat = new VFloatElements();
		this.pEFloat = new EFloatElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.vmsc.Vmsc".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//VPackage returns VPackage:
	//    {VPackage}
	//    'VPackage' ':'
	//    '{'
	//    'name' ':' name=EString (',' | '}')
	//        ('VPrefix' ':' VPrefix=EString ',')
	//        ('VUri' ':' VUri=EString ',')
	//        ('VComponents' ':' '[' '{' VComponents+=VStructuralComponent '}' ( ',' '{' VComponents+=VStructuralComponent '}')* ']' )?
	//    '}'
	//    ;
	public VPackageElements getVPackageAccess() {
		return pVPackage;
	}
	
	public ParserRule getVPackageRule() {
		return getVPackageAccess().getRule();
	}
	
	//VStructuralComponent returns VStructuralComponent:
	//    VEnum | VDatatype_Impl | VPackage | VClass;
	public VStructuralComponentElements getVStructuralComponentAccess() {
		return pVStructuralComponent;
	}
	
	public ParserRule getVStructuralComponentRule() {
		return getVStructuralComponentAccess().getRule();
	}
	
	//VStructuralFeatures returns VStructuralFeatures:
	//    VAttribute | VReference;
	public VStructuralFeaturesElements getVStructuralFeaturesAccess() {
		return pVStructuralFeatures;
	}
	
	public ParserRule getVStructuralFeaturesRule() {
		return getVStructuralFeaturesAccess().getRule();
	}
	
	//VType returns VType:
	//    VString | VInt | VFloat;
	public VTypeElements getVTypeAccess() {
		return pVType;
	}
	
	public ParserRule getVTypeRule() {
		return getVTypeAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//VEnum returns VEnum:
	//    {VEnum}
	//    'VEnum' ':'
	//    '{'
	//    'name' ':' name=EString ','
	//    (IsSerializable?='IsSerializable' ':' 'True' ',')?
	//    '}'
	//    ;
	public VEnumElements getVEnumAccess() {
		return pVEnum;
	}
	
	public ParserRule getVEnumRule() {
		return getVEnumAccess().getRule();
	}
	
	//VDatatype_Impl returns VDatatype:
	//    {VDatatype}
	//    'VDatatype' ':'
	//    '{'
	//    'name' ':' name=EString ','
	//    (IsSerializable?='IsSerializable' ':' 'True' ',')?
	//    '}'
	//    ;
	public VDatatype_ImplElements getVDatatype_ImplAccess() {
		return pVDatatype_Impl;
	}
	
	public ParserRule getVDatatype_ImplRule() {
		return getVDatatype_ImplAccess().getRule();
	}
	
	//VClass returns VClass:
	//    {VClass}
	//    'VClass' ':'
	//    '{'
	//    'name' ':' name=EString ','
	//    ('VStructuralFeatures' ':' '[' '{' VStructural_features+=VStructuralFeatures '}' ( ',' '{' VStructural_features+=VStructuralFeatures '}')*  ']' ',')?
	//    ('VSuperType' ':' '['  VSuperType+=[VClass|EString] ( ',' VSuperType+=[VClass|EString])* ']' ',')?
	//    (IsAbstract?='IsAbstract' ':' 'True' ',')?
	//    (IsInterface?='IsInterface' ':' 'True' ',')?
	//    '}';
	public VClassElements getVClassAccess() {
		return pVClass;
	}
	
	public ParserRule getVClassRule() {
		return getVClassAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//VAttribute returns VAttribute:
	//    {VAttribute}
	//    'VAttribute' ':'
	//    '{'
	//    'name' ':' name=EString ','
	//    (IsChangeable?='IsChangeable')?
	//    (IsOrdered?='IsOrdered')?
	//    (IsTransient?='IsTransient')?
	//    (IsUnsettable?='IsUnsettable')?
	//    (IsVolatile?='IsVolatile')?
	//    (IsDerived?='IsDerived')?
	//    (IsUnique?='IsUnique')?
	//        ('LowerBound' ':' LowerBound=EInt ',')?
	//        ('UpperBound' ':' UpperBound=EInt ',')?
	//        ('VType' ':' VType=VType)?
	//    '}';
	public VAttributeElements getVAttributeAccess() {
		return pVAttribute;
	}
	
	public ParserRule getVAttributeRule() {
		return getVAttributeAccess().getRule();
	}
	
	//VReference returns VReference:
	//    {VReference}
	//    'VReference' ':'
	//    '{'
	//    'name' ':' name=EString ','
	//    (IsChangeable?='IsChangeable' ':' 'True' ',')?
	//    (IsOrdered?='IsOrdered' ':' 'True' ',')?
	//    (IsTransient?='IsTransient' ':' 'True' ',')?
	//    (IsUnsettable?='IsUnsettable' ':' 'True' ',')?
	//    (IsVolatile?='IsVolatile' ':' 'True' ',')?
	//    (IsDerived?='IsDerived' ':' 'True' ',')?
	//    (IsUnique?='IsUnique' ':' 'True' ',')?
	//    (IsContainer?='IsContainer' ':' 'True' ',')?
	//    (IsContainment?='IsContainment' ':' 'True' ',')?
	//        ('LowerBound' ':' LowerBound=EInt ',')?
	//        ('UpperBound' ':' UpperBound=EInt ',')?
	//        ('VType' ':' VType=VClass)?
	//    '}';
	public VReferenceElements getVReferenceAccess() {
		return pVReference;
	}
	
	public ParserRule getVReferenceRule() {
		return getVReferenceAccess().getRule();
	}
	
	//VString returns VString:
	//    {VString}
	//    'VString'
	//    ','
	//    'VContent' ':' VContent=EString
	//    ','?;
	public VStringElements getVStringAccess() {
		return pVString;
	}
	
	public ParserRule getVStringRule() {
		return getVStringAccess().getRule();
	}
	
	//VInt returns VInt:
	//    {VInt}
	//    'VInt'
	//    ','
	//    'VContent' ':' VContent=EInt
	//    ','?;
	public VIntElements getVIntAccess() {
		return pVInt;
	}
	
	public ParserRule getVIntRule() {
		return getVIntAccess().getRule();
	}
	
	//VFloat returns VFloat:
	//    {VFloat}
	//    'VFloat'
	//    ','
	//    'VContent' ':' VContent=EFloat
	//    ','?;
	public VFloatElements getVFloatAccess() {
		return pVFloat;
	}
	
	public ParserRule getVFloatRule() {
		return getVFloatAccess().getRule();
	}
	
	//EFloat returns ecore::EFloat:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
