on:
  push:
    branches:
      - lspFeature

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: xvfb-run -a npm test2
        if: runner.os == 'Linux'
      - run: npm test2
        if: runner.os != 'Linux'
      - name: TypeScript Linter Action
        # You may pin to the exact commit or the version.
        # uses: AntonKornus/TypeScript-Linter@c76df0ed4b1f5e93f202195ebd6d03bfe12fe837
        uses: AntonKornus/TypeScript-Linter@1.0.0
        with:
          # Set your default working directory
          folder: ./server/Vmsc
      
